-- supabase/seed.sql
-- GENERATED by scripts/crawl-catalog.ts — DO NOT EDIT BY HAND.
-- Regenerate with: bun run crawl:catalog
--
-- Point-in-time snapshot (2026-07-07T09:36:09.374Z) of the currently popular,
-- REAL provider / skill / mcp entries crawled from public sources:
--   provider → OpenRouter, skill → GitHub, mcp → PulseMCP.
-- Plus the 3 fixed TEST providers (local / yls / skyapi, tagged 'test').
-- Counts: mcp=10, provider=10, skill=10 (+3 test providers).

-- ── Publishers (test publishers + crawled) ──────────────────────────────────
INSERT INTO publishers (slug, name, avatar_url, tier, bio) VALUES
  ('agent-store', 'Agent Store', 'https://api.dicebear.com/9.x/shapes/svg?seed=agent-store', 'official', 'Agent Store 官方内置组件。'),
  ('yls-me', 'YLS.me', 'https://api.dicebear.com/9.x/shapes/svg?seed=yls', 'verified', '已验证的第三方模型中转服务。'),
  ('skyapi', 'SkyAPI', 'https://api.dicebear.com/9.x/shapes/svg?seed=skyapi', 'community', '稳定线路、免翻墙接入 Claude Code 的第三方中转服务。'),
  ('affaan-m', 'affaan-m', 'https://avatars.githubusercontent.com/u/124439313?v=4', 'community', NULL),
  ('agenttrust', 'agenttrust', 'https://github.com/agenttrust.png', 'community', NULL),
  ('akashml', 'AkashML', 'https://api.dicebear.com/9.x/shapes/svg?seed=akashml', 'community', NULL),
  ('ankimcp', 'ankimcp', 'https://github.com/ankimcp.png', 'community', NULL),
  ('anomalyarmor', 'anomalyarmor', 'https://github.com/anomalyarmor.png', 'community', NULL),
  ('arcee-ai', 'Arcee AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=arcee-ai', 'community', NULL),
  ('boolsai-ai', 'Boolsai-ai', 'https://github.com/Boolsai-ai.png', 'community', NULL),
  ('breverdbidder', 'breverdbidder', 'https://github.com/breverdbidder.png', 'community', NULL),
  ('cerebras', 'Cerebras', 'https://api.dicebear.com/9.x/shapes/svg?seed=cerebras', 'community', NULL),
  ('community', 'Community', 'https://api.dicebear.com/9.x/shapes/svg?seed=community', 'community', NULL),
  ('dealfluence', 'dealfluence', 'https://github.com/dealfluence.png', 'community', NULL),
  ('frumu-ai', 'frumu-ai', 'https://github.com/frumu-ai.png', 'community', NULL),
  ('morph', 'Morph', 'https://api.dicebear.com/9.x/shapes/svg?seed=morph', 'community', NULL),
  ('openai', 'OpenAI', 'https://api.dicebear.com/9.x/shapes/svg?seed=openai', 'official', NULL),
  ('reka', 'Reka', 'https://api.dicebear.com/9.x/shapes/svg?seed=reka', 'community', NULL),
  ('sambanova', 'SambaNova', 'https://api.dicebear.com/9.x/shapes/svg?seed=sambanova', 'community', NULL),
  ('stealth', 'Stealth', 'https://api.dicebear.com/9.x/shapes/svg?seed=stealth', 'community', NULL),
  ('stepfun', 'StepFun', 'https://api.dicebear.com/9.x/shapes/svg?seed=stepfun', 'community', NULL),
  ('techdocsstudio', 'TechDocsStudio', 'https://github.com/TechDocsStudio.png', 'community', NULL),
  ('z-ai', 'Z.AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=z-ai', 'community', NULL);

-- ── TEST providers (always present, real configs) ───────────────────────────
-- Provider: local (built-in relay) — the endpoint Claude/Codex point at; forwards
-- to upstream providers by level. No upstream API key. Rendered specially in the
-- CLI client (LOCAL_PROVIDER_SENTINEL __local__); this catalog row is its store listing.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'local',
  '本地中转',
  '内置本地中转：将 Claude Code / Codex 的 baseURL 指向本机监听端口，请求按 Level 优先级转发到已配置的上游供应商，失败自动降级。无需 API 密钥。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'agent-store'),
  ARRAY['claude','codex'], ARRAY['relay','local','内置','test'], 0, 5.0, 'published',
  $${"steps":[]}$$,
  $${"configSchema":{},"supportedModels":[]}$$
);

-- Provider: yls (伊莉思 Code) — real China relay for Codex CLI. Pre-fills the codex
-- endpoint connection on install; user supplies the Bearer API key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'yls',
  'YLS Code 中转',
  '伊莉思 Code 中转服务，国内直连免翻墙接入 Codex CLI（GPT-5 Code）与 Claude Code；此预设接入其 Codex 端点，按订阅计费。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'yls-me'),
  ARRAY['codex'], ARRAY['relay','codex','国产中转','test'], 32000, 4.7, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"https://code.ylsagi.com/codex","authType":"bearer","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (Bearer)"},"baseUrl":{"type":"string","description":"API 地址","default":"https://code.ylsagi.com/codex"},"authType":{"type":"string","default":"bearer"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["gpt-5-codex","gpt-5"]}$$
);

-- Provider: skyapi — real China relay for Claude Code (Anthropic protocol). Pre-fills
-- the claude endpoint connection on install; user supplies the x-api-key.
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skyapi',
  'SkyAPI 中转',
  'SkyAPI 中转服务，稳定线路免翻墙接入 Claude Code，兼容 Cursor / Cline / Windsurf 等客户端。',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'skyapi'),
  ARRAY['claude'], ARRAY['relay','claude','国产中转','test'], 21000, 4.5, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"http://150.158.2.79:8888","authType":"anthropic","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (x-api-key)"},"baseUrl":{"type":"string","description":"API 地址","default":"http://150.158.2.79:8888"},"authType":{"type":"string","default":"anthropic"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["claude-opus-4-8","claude-sonnet-5","claude-haiku-4-5-20251001","claude-opus-4-5"]}$$
);

-- ── Crawled items (real, popularity-ranked) ─────────────────────────────────
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ankimcp-anki-mcp-server', 'Anki MCP Server', 'MCP server for Anki flashcards: adaptive review, notes, media, and deck management via AnkiConnect.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'ankimcp'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 370, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @ankimcp/anki-mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'adeu-mcp-server', 'adeu', 'Automated DOCX Redlining Engine',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'dealfluence'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 118, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @adeu/mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'docs-mcp', 'docs-mcp', 'Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'frumu-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 109, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://tandem.ac/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'biel-ai', 'Biel.ai', 'Query your product docs from AI tools. Source-cited answers from your indexed documentation.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'techdocsstudio'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 3, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.biel.ai/v2/{project_slug}/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'agenttrust-mcp-server', 'AgentTrust — Identity & Trust for A2A Agents', 'Identity, trust, and A2A orchestration for autonomous AI agents. Official A2A partner.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'agenttrust'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @agenttrust/mcp-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'armor-mcp', 'AnomalyArmor', 'Data observability tools for engineering teams: alerts, freshness, schema drift, lineage, quality.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'anomalyarmor'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.anomalyarmor.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'biddeed-mcp', 'BidDeed MCP', 'AI-powered foreclosure auction intelligence for Florida counties via MCP tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'breverdbidder'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://mcp.biddeed.ai/api/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'directory', 'Boolsai Directory', 'Indexed ecommerce site directory — vendor lookups, brands by city/market/founder. 10 tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'boolsai-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://directory.boolsai.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'grep', 'Boolsai Grep', 'Parallel regex across all Boolsai scans — discover new vendor patterns, niche signals. 4 tools.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'boolsai-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 1, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://grep.boolsai.ai/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'mcp', 'inference.sh', 'Run 150+ AI apps — image, video, audio, LLMs, 3D and more. Browse, execute, stream results.',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'community'),
  ARRAY['claude','codex'], ARRAY['mcp','streamable-http'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"http","url":"https://sh.inference.ac","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'arcee-ai-provider', 'Arcee AI', 'Arcee AI：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'arcee-ai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'sambanova-provider', 'SambaNova', 'SambaNova：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'sambanova'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'reka-provider', 'Reka', 'Reka：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'reka'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'cerebras-provider', 'Cerebras', 'Cerebras：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'cerebras'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'morph-provider', 'Morph', 'Morph：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'morph'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'stealth-provider', 'Stealth', 'Stealth：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'stealth'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'akashml-provider', 'AkashML', 'AkashML：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'akashml'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'openai-provider', 'OpenAI', 'OpenAI：OpenRouter 上的真实推理服务供应商（总部 US）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'openai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'z-ai-provider', 'Z.AI', 'Z.AI：OpenRouter 上的真实推理服务供应商（总部 SG）。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'z-ai'),
  ARRAY['claude','codex'], ARRAY['provider','sg'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'stepfun-provider', 'StepFun', 'StepFun：OpenRouter 上的真实推理服务供应商。',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'stepfun'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-introspection-debugging', 'agent-introspection-debugging', 'Structured self-debugging workflow for AI agent failures using capture, diagnosis, contained recovery, and introspection reports.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-introspection-debugging/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-introspection-debugging/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-agent-sort', 'agent-sort', 'Build an evidence-backed ECC install plan for a specific repo by sorting skills, commands, rules, hooks, and extras into DAILY vs LIBRARY buckets using parallel repo-aware review passes. Use when ECC should be trimmed to what a project actually needs instead of loading the full bundle.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/agent-sort/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/agent-sort/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-api-design', 'api-design', 'REST API design patterns including resource naming, status codes, pagination, filtering, error responses, versioning, and rate limiting for production APIs.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/api-design/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/api-design/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-article-writing', 'article-writing', 'Write articles, guides, blog posts, tutorials, newsletter issues, and other long-form content in a distinctive voice derived from supplied examples or brand guidance. Use when the user wants polished written content longer than a paragraph, especially when voice consistency, structure, and credibili',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/article-writing/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/article-writing/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/article-writing/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-backend-patterns', 'backend-patterns', 'Backend architecture patterns, API design, database optimization, and server-side best practices for Node.js, Express, and Next.js API routes.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/backend-patterns/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/backend-patterns/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/backend-patterns/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-benchmark-methodology', 'benchmark-methodology', '>-',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/benchmark-methodology/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/benchmark-methodology/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/benchmark-methodology/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-brand-discovery', 'brand-discovery', '>-',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-discovery/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-discovery/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/brand-discovery/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-brand-voice', 'brand-voice', 'Build a source-derived writing style profile from real posts, essays, launch notes, docs, or site copy, then reuse that profile across content, outreach, and social workflows. Use when the user wants voice consistency without generic AI writing tropes.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-voice/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/brand-voice/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/brand-voice/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-bun-runtime', 'bun-runtime', 'Bun as runtime, package manager, bundler, and test runner. When to choose Bun vs Node, migration notes, and Vercel support.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/bun-runtime/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/bun-runtime/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/bun-runtime/SKILL.md"}}'::jsonb
);
INSERT INTO items (
  slug, name, description,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc-coding-standards', 'coding-standards', 'Baseline cross-project coding conventions for naming, readability, immutability, and code-quality review. Use detailed frontend or backend skills for framework-specific patterns.',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['skill'], 226806, 0, 'published',
  '{"steps":[{"type":"file","url":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/coding-standards/SKILL.md","dest":"skill.md"}]}'::jsonb, '{"contentUrl":"https://raw.githubusercontent.com/affaan-m/ECC/main/.agents/skills/coding-standards/SKILL.md","source":{"repo":"affaan-m/ECC","ref":"main","path":".agents/skills/coding-standards/SKILL.md"}}'::jsonb
);

