-- supabase/seed.sql
-- GENERATED by scripts/crawl-catalog.ts — DO NOT EDIT BY HAND.
-- Regenerate with: bun run crawl:catalog
--
-- Point-in-time snapshot (2026-07-06T05:11:57.203Z) of the currently popular,
-- REAL provider / skill / mcp entries crawled from public sources:
--   provider → OpenRouter, skill → GitHub, mcp → PulseMCP.
-- Plus the 3 fixed TEST providers (local / yls / skyapi, tagged 'test').
-- Counts: mcp=10, provider=10, skill=10 (+3 test providers).

-- ── Publishers (test publishers + crawled) ──────────────────────────────────
INSERT INTO publishers (slug, name, avatar_url, tier, bio) VALUES
  ('agent-store', 'Agent Store', 'https://api.dicebear.com/9.x/shapes/svg?seed=agent-store', 'official', 'Agent Store 官方内置组件。'),
  ('yls-me', 'YLS.me', 'https://api.dicebear.com/9.x/shapes/svg?seed=yls', 'verified', '已验证的第三方模型中转服务。'),
  ('skyapi', 'SkyAPI', 'https://api.dicebear.com/9.x/shapes/svg?seed=skyapi', 'community', '稳定线路、免翻墙接入 Claude Code 的第三方中转服务。'),
  ('affaan-m', 'affaan-m', 'https://avatars.githubusercontent.com/u/124439313?v=4', 'community', NULL),
  ('akashml', 'AkashML', 'https://api.dicebear.com/9.x/shapes/svg?seed=akashml', 'community', NULL),
  ('arcee-ai', 'Arcee AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=arcee-ai', 'community', NULL),
  ('cerebras', 'Cerebras', 'https://api.dicebear.com/9.x/shapes/svg?seed=cerebras', 'community', NULL),
  ('chromedevtools', 'chromedevtools', 'https://github.com/chromedevtools.png', 'community', NULL),
  ('composiohq', 'ComposioHQ', 'https://avatars.githubusercontent.com/u/128464815?v=4', 'community', NULL),
  ('czlonkowski', 'czlonkowski', 'https://github.com/czlonkowski.png', 'community', NULL),
  ('deusdata', 'deusdata', 'https://github.com/deusdata.png', 'community', NULL),
  ('graphify-labs', 'Graphify-Labs', 'https://avatars.githubusercontent.com/u/297659074?v=4', 'community', NULL),
  ('juliusbrussee', 'JuliusBrussee', 'https://avatars.githubusercontent.com/u/104168679?v=4', 'community', NULL),
  ('leonxlnx', 'Leonxlnx', 'https://avatars.githubusercontent.com/u/219127460?v=4', 'community', NULL),
  ('mastra-ai', 'mastra-ai', 'https://github.com/mastra-ai.png', 'community', NULL),
  ('mattpocock', 'mattpocock', 'https://avatars.githubusercontent.com/u/28293365?v=4', 'community', NULL),
  ('microsoft', 'microsoft', 'https://github.com/microsoft.png', 'community', NULL),
  ('modelcontextprotocol', 'modelcontextprotocol', 'https://github.com/modelcontextprotocol.png', 'official', NULL),
  ('moonshotai', 'Moonshot AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=moonshotai', 'community', NULL),
  ('morph', 'Morph', 'https://api.dicebear.com/9.x/shapes/svg?seed=morph', 'community', NULL),
  ('multica-ai', 'multica-ai', 'https://avatars.githubusercontent.com/u/254743058?v=4', 'community', NULL),
  ('mvanhorn', 'mvanhorn', 'https://avatars.githubusercontent.com/u/455140?v=4', 'community', NULL),
  ('nextlevelbuilder', 'nextlevelbuilder', 'https://avatars.githubusercontent.com/u/246974152?v=4', 'community', NULL),
  ('openai', 'OpenAI', 'https://api.dicebear.com/9.x/shapes/svg?seed=openai', 'official', NULL),
  ('reka', 'Reka', 'https://api.dicebear.com/9.x/shapes/svg?seed=reka', 'community', NULL),
  ('sambanova', 'SambaNova', 'https://api.dicebear.com/9.x/shapes/svg?seed=sambanova', 'community', NULL),
  ('santifer', 'santifer', 'https://avatars.githubusercontent.com/u/256850418?v=4', 'community', NULL),
  ('stealth', 'Stealth', 'https://api.dicebear.com/9.x/shapes/svg?seed=stealth', 'community', NULL),
  ('upstash', 'upstash', 'https://github.com/upstash.png', 'community', NULL),
  ('z-ai', 'Z.AI', 'https://api.dicebear.com/9.x/shapes/svg?seed=z-ai', 'community', NULL);

-- ── TEST providers (always present, real configs) ───────────────────────────
-- Provider: local (built-in relay) — the endpoint Claude/Codex point at; forwards
-- to upstream providers by level. No upstream API key. Rendered specially in the
-- CLI client (LOCAL_PROVIDER_SENTINEL __local__); this catalog row is its store listing.
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'local',
  '本地中转',
  '内置本地中转：将 Claude Code / Codex 的 baseURL 指向本机监听端口，请求按 Level 优先级转发到已配置的上游供应商，失败自动降级。无需 API 密钥。',
  'https://example.com/readme/local.md',
  'https://api.dicebear.com/9.x/icons/svg?seed=local-relay',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'agent-store'),
  ARRAY['claude','codex'], ARRAY['relay','local','内置','test'], 0, 5.0, 'published',
  $${"steps":[]}$$,
  $${"configSchema":{},"supportedModels":[]}$$
);

-- Provider: yls (伊莉思 Code) — real China relay for Codex CLI. Pre-fills the codex
-- endpoint connection on install; user supplies the Bearer API key.
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'yls',
  'YLS Code 中转',
  '伊莉思 Code 中转服务，国内直连免翻墙接入 Codex CLI（GPT-5 Code）与 Claude Code；此预设接入其 Codex 端点，按订阅计费。',
  'https://docs.ylsagi.io/',
  'https://api.dicebear.com/9.x/icons/svg?seed=yls-code',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'yls-me'),
  ARRAY['codex'], ARRAY['relay','codex','国产中转','test'], 32000, 4.7, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"https://code.ylsagi.com/codex","authType":"bearer","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (Bearer)"},"baseUrl":{"type":"string","description":"API 地址","default":"https://code.ylsagi.com/codex"},"authType":{"type":"string","default":"bearer"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["gpt-5-codex","gpt-5"]}$$
);

-- Provider: skyapi — real China relay for Claude Code (Anthropic protocol). Pre-fills
-- the claude endpoint connection on install; user supplies the x-api-key.
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skyapi',
  'SkyAPI 中转',
  'SkyAPI 中转服务，稳定线路免翻墙接入 Claude Code，兼容 Cursor / Cline / Windsurf 等客户端。',
  'https://www.skyapi.org/docs/zh-CN/',
  'https://api.dicebear.com/9.x/icons/svg?seed=skyapi',
  'provider', '1.0.0',
  (SELECT id FROM publishers WHERE slug = 'skyapi'),
  ARRAY['claude'], ARRAY['relay','claude','国产中转','test'], 21000, 4.5, 'published',
  $${"steps":[{"type":"config","patch":{"apiKey":"","baseUrl":"http://150.158.2.79:8888","authType":"anthropic","upstreamProtocol":"auto","level":1}}]}$$,
  $${"configSchema":{"type":"object","required":["apiKey"],"properties":{"apiKey":{"type":"string","description":"API 密钥 (x-api-key)"},"baseUrl":{"type":"string","description":"API 地址","default":"http://150.158.2.79:8888"},"authType":{"type":"string","default":"anthropic"},"upstreamProtocol":{"type":"string","default":"auto"},"level":{"type":"number","default":1}}},"supportedModels":["claude-opus-4-8","claude-sonnet-5","claude-haiku-4-5-20251001","claude-opus-4-5"]}$$
);

-- ── Crawled items (real, popularity-ranked) ─────────────────────────────────
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'playwright-mcp', 'Playwright Browser Automation', 'Enables web browser control for navigating websites, capturing page snapshots, interacting with elements, and taking screenshots through Playwright''s automation capabilities.', 'https://github.com/microsoft/playwright-mcp', 'https://github.com/microsoft.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'microsoft'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 83762772, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @playwright/mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'chrome-devtools-mcp', 'Chrome DevTools', 'Provides direct Chrome browser control through DevTools for web automation, debugging, and performance analysis using accessibility tree snapshots for reliable element targeting, automatic page event handling, and integrated performance tracing with actionable insights.', 'https://github.com/chromedevtools/chrome-devtools-mcp', 'https://github.com/chromedevtools.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'chromedevtools'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 31853517, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y chrome-devtools-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'upstash-context7-mcp', 'Context7 (Documentation Database)', 'Connects to Context7.com''s documentation database to provide up-to-date library and framework documentation with intelligent project ranking and customizable token limits.', 'https://github.com/upstash/context7', 'https://github.com/upstash.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'upstash'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 25020069, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @upstash/context7-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'modelcontextprotocol-server-filesystem', 'Filesystem', 'Read, write, and manipulate local files through a controlled API.', 'https://github.com/modelcontextprotocol/servers/tree/HEAD/src/filesystem', 'https://github.com/modelcontextprotocol.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'modelcontextprotocol'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 11219241, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @modelcontextprotocol/server-filesystem","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'modelcontextprotocol-server-sequential-thinking', 'Sequential Thinking', 'Implements a structured sequential thinking process for breaking down complex problems, iteratively refining solutions, and exploring multiple reasoning paths.', 'https://github.com/modelcontextprotocol/servers/tree/HEAD/src/sequentialthinking', 'https://github.com/modelcontextprotocol.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'modelcontextprotocol'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 5620989, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @modelcontextprotocol/server-sequential-thinking","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'modelcontextprotocol-server-memory', 'Knowledge Graph Memory', 'Build and query persistent semantic networks for data management.', 'https://github.com/modelcontextprotocol/servers/tree/HEAD/src/memory', 'https://github.com/modelcontextprotocol.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'modelcontextprotocol'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 3258998, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @modelcontextprotocol/server-memory","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'n8n-mcp', 'n8n', 'Integrates with n8n workflow automation platform to provide conversational access to 525+ nodes including AI-capable nodes and triggers, enabling natural language workflow creation, validation, and management without requiring direct platform knowledge.', 'https://github.com/czlonkowski/n8n-mcp', 'https://github.com/czlonkowski.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'czlonkowski'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 3168515, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y n8n-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'modelcontextprotocol-server-everything', 'Demo (Everything)', 'Test protocol features and tools for client compatibility.', 'https://github.com/modelcontextprotocol/servers/tree/HEAD/src/everything', 'https://github.com/modelcontextprotocol.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'modelcontextprotocol'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 2194759, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @modelcontextprotocol/server-everything","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'mastra-mcp-docs-server', 'Mastra Docs', 'Provides AI assistants with direct access to Mastra.ai''s complete knowledge base.', 'https://github.com/mastra-ai/mastra/tree/HEAD/packages/mcp-docs-server', 'https://github.com/mastra-ai.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'mastra-ai'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 716791, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y @mastra/mcp-docs-server","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'codebase-memory-mcp', 'Codebase Memory', 'Codebase knowledge graph for AI agents — 159 languages, sub-ms queries, 99% fewer tokens.', 'https://github.com/deusdata/codebase-memory-mcp', 'https://github.com/deusdata.png',
  'mcp', '1.0.0', (SELECT id FROM publishers WHERE slug = 'deusdata'),
  ARRAY['claude','codex'], ARRAY['mcp','npm'], 10205, 0, 'published',
  '{"steps":[]}'::jsonb, '{"transport":"stdio","serverCommand":"npx -y codebase-memory-mcp","configSchema":{}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'arcee-ai-provider', 'Arcee AI', 'Arcee AI：OpenRouter 上的真实推理服务供应商（总部 US）。', 'https://openrouter.ai/', 'https://api.dicebear.com/9.x/icons/svg?seed=arcee-ai-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'arcee-ai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'sambanova-provider', 'SambaNova', 'SambaNova：OpenRouter 上的真实推理服务供应商（总部 US）。', 'https://status.sambanova.ai/', 'https://api.dicebear.com/9.x/icons/svg?seed=sambanova-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'sambanova'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'reka-provider', 'Reka', 'Reka：OpenRouter 上的真实推理服务供应商。', 'https://reka.ai/legal/terms-of-use', 'https://api.dicebear.com/9.x/icons/svg?seed=reka-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'reka'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'cerebras-provider', 'Cerebras', 'Cerebras：OpenRouter 上的真实推理服务供应商（总部 US）。', 'https://www.cerebras.ai/terms-of-service', 'https://api.dicebear.com/9.x/icons/svg?seed=cerebras-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'cerebras'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'morph-provider', 'Morph', 'Morph：OpenRouter 上的真实推理服务供应商（总部 US）。', 'https://www.morphllm.com/privacy/tos', 'https://api.dicebear.com/9.x/icons/svg?seed=morph-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'morph'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'stealth-provider', 'Stealth', 'Stealth：OpenRouter 上的真实推理服务供应商。', 'https://openrouter.ai/', 'https://api.dicebear.com/9.x/icons/svg?seed=stealth-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'stealth'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'akashml-provider', 'AkashML', 'AkashML：OpenRouter 上的真实推理服务供应商。', 'https://akashml.com/terms', 'https://api.dicebear.com/9.x/icons/svg?seed=akashml-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'akashml'),
  ARRAY['claude','codex'], ARRAY['provider'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'moonshotai-provider', 'Moonshot AI', 'Moonshot AI：OpenRouter 上的真实推理服务供应商（总部 SG）。', 'https://platform.moonshot.ai/docs/agreement/modeluse', 'https://api.dicebear.com/9.x/icons/svg?seed=moonshotai-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'moonshotai'),
  ARRAY['claude','codex'], ARRAY['provider','sg'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'openai-provider', 'OpenAI', 'OpenAI：OpenRouter 上的真实推理服务供应商（总部 US）。', 'https://status.openai.com/', 'https://api.dicebear.com/9.x/icons/svg?seed=openai-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'openai'),
  ARRAY['claude','codex'], ARRAY['provider','us'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'z-ai-provider', 'Z.AI', 'Z.AI：OpenRouter 上的真实推理服务供应商（总部 SG）。', 'https://chat.z.ai/legal-agreement/terms-of-service', 'https://api.dicebear.com/9.x/icons/svg?seed=z-ai-provider',
  'provider', '1.0.0', (SELECT id FROM publishers WHERE slug = 'z-ai'),
  ARRAY['claude','codex'], ARRAY['provider','sg'], 0, 0, 'published',
  '{"steps":[]}'::jsonb, '{"configSchema":{},"supportedModels":[]}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ecc', 'ECC', 'The agent harness performance optimization system. Skills, instincts, memory, security, and research-first development for Claude Code, Codex, Opencode, Cursor and beyond.', 'https://github.com/affaan-m/ECC', 'https://avatars.githubusercontent.com/u/124439313?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'affaan-m'),
  ARRAY['claude'], ARRAY['ai-agents','anthropic','claude','claude-code','developer-tools','skill'], 226384, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"affaan-m/ECC","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'andrej-karpathy-skills', 'andrej-karpathy-skills', 'A single CLAUDE.md file to improve Claude Code behavior, derived from Andrej Karpathy''s observations on LLM coding pitfalls.', 'https://github.com/multica-ai/andrej-karpathy-skills', 'https://avatars.githubusercontent.com/u/254743058?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'multica-ai'),
  ARRAY['claude'], ARRAY['skill'], 188133, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"multica-ai/andrej-karpathy-skills","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'skills', 'skills', 'Skills for Real Engineers. Straight from my .claude directory.', 'https://github.com/mattpocock/skills', 'https://avatars.githubusercontent.com/u/28293365?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'mattpocock'),
  ARRAY['claude'], ARRAY['skill'], 157731, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"mattpocock/skills","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'ui-ux-pro-max-skill', 'ui-ux-pro-max-skill', 'An AI SKILL that provide design intelligence for building professional UI/UX multiple platforms', 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill', 'https://avatars.githubusercontent.com/u/246974152?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'nextlevelbuilder'),
  ARRAY['claude'], ARRAY['ai-skills','antigravity','claude','claude-code','codex','skill'], 101334, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"nextlevelbuilder/ui-ux-pro-max-skill","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'caveman', 'caveman', '🪨 why use many token when few token do trick — Claude Code skill that cuts 65% of tokens by talking like caveman', 'https://github.com/JuliusBrussee/caveman', 'https://avatars.githubusercontent.com/u/104168679?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'juliusbrussee'),
  ARRAY['claude'], ARRAY['ai','anthropic','caveman','claude','claude-code','skill'], 85070, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"JuliusBrussee/caveman","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'graphify', 'graphify', 'AI coding assistant skill (Claude Code, Codex, OpenCode, Cursor, Gemini CLI, and more). Turn any folder of code, SQL schemas, R scripts, shell scripts, docs, papers, images, or videos into a queryable knowledge graph. App code + database schema + infrastructure in one graph.', 'https://github.com/Graphify-Labs/graphify', 'https://avatars.githubusercontent.com/u/297659074?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'graphify-labs'),
  ARRAY['claude'], ARRAY['antigravity','claude-code','codex','gemini','graphrag','skill'], 78245, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"Graphify-Labs/graphify","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'awesome-claude-skills', 'awesome-claude-skills', 'A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows', 'https://github.com/ComposioHQ/awesome-claude-skills', 'https://avatars.githubusercontent.com/u/128464815?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'composiohq'),
  ARRAY['claude'], ARRAY['agent-skills','ai-agents','antigravity','automation','claude','skill'], 66922, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"ComposioHQ/awesome-claude-skills","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'career-ops', 'career-ops', 'AI-powered job search system built on Claude Code. 14 skill modes, Go dashboard, PDF generation, batch processing.', 'https://github.com/santifer/career-ops', 'https://avatars.githubusercontent.com/u/256850418?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'santifer'),
  ARRAY['claude'], ARRAY['ai-agent','anthropic','automation','beginner-friendly','career','skill'], 58710, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"santifer/career-ops","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'taste-skill', 'taste-skill', 'Taste-Skill - gives your AI good taste. stops the AI from generating boring, generic slop ', 'https://github.com/Leonxlnx/taste-skill', 'https://avatars.githubusercontent.com/u/219127460?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'leonxlnx'),
  ARRAY['claude'], ARRAY['agent','ai','claude','claude-code','codex','skill'], 57814, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"Leonxlnx/taste-skill","ref":"main"}}'::jsonb
);
INSERT INTO items (
  slug, name, description, readme_url, icon,
  category, version, publisher_id,
  compatible_with, tags, downloads, rating, status,
  install_hook, metadata
) VALUES (
  'last30days-skill', 'last30days-skill', 'AI agent skill that researches any topic across Reddit, X, YouTube, HN, Polymarket, and the web - then synthesizes a grounded summary', 'https://github.com/mvanhorn/last30days-skill', 'https://avatars.githubusercontent.com/u/455140?v=4',
  'skill', '1.0.0', (SELECT id FROM publishers WHERE slug = 'mvanhorn'),
  ARRAY['claude'], ARRAY['ai-prompts','ai-skill','bluesky','claude','claude-code','skill'], 49223, 0, 'published',
  '{"steps":[]}'::jsonb, '{"source":{"repo":"mvanhorn/last30days-skill","ref":"main"}}'::jsonb
);

