// Desktop UI translations. Each locale mirrors the same nested key structure;
// missing keys fall back to Chinese (see resolve() in ./index.tsx). Grown
// incrementally as components are externalized.

export const LOCALES = ['zh', 'en', 'ja', 'ko', 'es'] as const
export type Locale = (typeof LOCALES)[number]

type Dict = Record<string, unknown>

const zh: Dict = {
  detail: { selectHint: '从左侧选择一个资源查看详情', installedPrefix: '已安装', favorite: '收藏', unfavorite: '取消收藏', copyCmd: '复制安装命令', configCountSuffix: '份配置 · 在左侧列表展开该条目即可管理', quality: '质量', tabReview: '审查', tabVersion: '版本', qualityScore: '质量评分', reviewPoints: '审查要点', autoReviewNote: '由自动质量与安全审查生成 · 用户评价系统尚未上线', noReview: '暂无自动审查记录', userReviews: '用户评价', anon: '匿名', reviewOnWeb: '在网页版商店可发表评价', currentVersion: '当前版本', riskLow: '低风险', riskMedium: '中等风险', riskHigh: '高风险' },
  health: { title: '供应商健康', coolingSuffix: '冷却中', cooldown: '冷却', recoverNow: '立即恢复', healthy: '正常', minutes: '分钟', seconds: '秒', errAuth: '认证失败', errRate: '被限流', errOverload: '过载', errServer: '服务端错误', errNetwork: '网络错误' },
  budget: { title: '本月预算', sub: '消费预算与告警', edit: '编辑', placeholder: '设置月度预算，留空表示不限', ariaLabel: '月度预算', projected: '预计月末', overBudget: '已超出预算', nearLimit: '接近预算上限' },
  usage: { exported: '已导出到', exportFailed: '导出失败', exportLabel: '导出近 30 天用量账单' },
  proxyLog: { title: '本地代理 · 请求日志', sub: '按 Level 顺序转发，失败自动降级', fallback: '降级' },
  overview: { trend: '消耗趋势', trendSub: '用量数据统计', today: '今日', last7: '近 7 天', last30: '近 30 天', totalCost: '总费用', totalTokens: '总 Tokens', totalRequests: '总请求数', modelCount: '模型分布', running: '运行中', stopped: '已停止', listenAddr: '监听地址', todayRequests: '今日请求', successRate: '成功率', recentRequests: '最近请求', viewAll: '查看全部', fallback: '（降级）', updatesAvailable: '可更新', all: '全部', update: '更新' },
  pro: {
    budget: { title: '预算与超支告警', desc: '设置月度消费预算，实时追踪本月花费、月末预测与超支提醒，并可导出账单。' },
    smartRouting: { title: '智能路由', desc: '多上游自动故障转移，主动避开正在冷却/限流的供应商，健康恢复后自动切回。Free 版为最多两路的基础降级。' },
    keyRotation: { title: '多 Key 轮换', desc: '为同一供应商配置多把密钥，Pro 会在请求之间轮换使用以分摊限流。' },
  },
  common: { install: '安装', installed: '已安装', cancel: '取消', save: '保存', saving: '保存中…', saved: '已保存', currentPrefix: '当前：' },
  nav: { store: '商店', overview: '概览', settings: '设置' },
  categories: { provider: '供应商', skill: '技能', mcp: 'MCP' },
  window: { close: '关闭', minimize: '最小化', maximize: '最大化' },
  settings: {
    title: '设置',
    close: '关闭',
    tabs: { account: '账户', general: '通用', about: '关于' },
    account: {
      notSignedIn: '未登录',
      signedIn: '已登录',
      disconnected: '未连接',
      logout: '退出登录',
      githubLogin: 'GitHub 登录',
      plan: '订阅计划',
      planPro: 'Pro · 无限私有资源 + 高级用量分析',
      planFree: 'Free · 升级解锁预算告警等 Pro 功能',
      upgrade: '升级 Pro',
      notConfigured: '登录未配置：缺少 VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY。',
      hint: '登录后可发布私有资源、跨设备同步已安装的技能 / MCP / 供应商 / 插件，并接收更新推送。',
    },
    general: { theme: '主题', dark: '暗色', light: '亮色', toggle: '切换', targetApp: '默认目标应用', language: '界面语言', languageSub: '选择界面显示语言' },
    about: { subtitle: 'registry client', docs: '文档', github: 'GitHub', checkUpdates: '检查更新', checking: '检查中…', upToDate: '已是最新', updatesSuffix: '个可更新', checkFailed: '检查失败' },
  },
}

const en: Dict = {
  detail: { selectHint: 'Select an item on the left to view details', installedPrefix: 'Installed', favorite: 'Favorite', unfavorite: 'Unfavorite', copyCmd: 'Copy install command', configCountSuffix: 'config(s) · expand this item in the left list to manage', quality: 'Quality', tabReview: 'Review', tabVersion: 'Versions', qualityScore: 'Quality score', reviewPoints: 'Review notes', autoReviewNote: 'Generated by automated quality & safety review · user reviews coming soon', noReview: 'No automated review yet', userReviews: 'User reviews', anon: 'Anonymous', reviewOnWeb: 'Post a review on the web store', currentVersion: 'Current version', riskLow: 'Low risk', riskMedium: 'Medium risk', riskHigh: 'High risk' },
  health: { title: 'Provider health', coolingSuffix: 'cooling', cooldown: 'Cooldown', recoverNow: 'Recover now', healthy: 'Healthy', minutes: 'min', seconds: 's', errAuth: 'Auth failed', errRate: 'Rate limited', errOverload: 'Overloaded', errServer: 'Server error', errNetwork: 'Network error' },
  budget: { title: "This month's budget", sub: 'spend budget & alerts', edit: 'Edit', placeholder: 'Set a monthly budget, leave blank for unlimited', ariaLabel: 'Monthly budget', projected: 'Projected month-end', overBudget: 'Over budget', nearLimit: 'Near budget limit' },
  usage: { exported: 'Exported to', exportFailed: 'Export failed', exportLabel: 'Export the last 30 days of usage' },
  proxyLog: { title: 'Local relay · request log', sub: 'Forwards in level order, auto-fallback on failure', fallback: 'Fallback' },
  overview: { trend: 'Usage trend', trendSub: 'Usage statistics', today: 'Today', last7: 'Last 7 days', last30: 'Last 30 days', totalCost: 'Total cost', totalTokens: 'Total tokens', totalRequests: 'Total requests', modelCount: 'Models', running: 'Running', stopped: 'Stopped', listenAddr: 'Listen address', todayRequests: "Today's requests", successRate: 'Success rate', recentRequests: 'Recent requests', viewAll: 'View all', fallback: ' (fallback)', updatesAvailable: 'Updates', all: 'All', update: 'Update' },
  pro: {
    budget: { title: 'Budget & overspend alerts', desc: 'Set a monthly spend budget with real-time tracking, month-end forecasts, overspend alerts, and billing export.' },
    smartRouting: { title: 'Smart routing', desc: 'Automatic failover across upstreams, proactively avoiding cooling/rate-limited providers and switching back when healthy. Free is basic two-upstream failover.' },
    keyRotation: { title: 'Key rotation', desc: 'Configure multiple keys per provider; Pro rotates across them per request to spread rate limits.' },
  },
  common: { install: 'Install', installed: 'Installed', cancel: 'Cancel', save: 'Save', saving: 'Saving…', saved: 'Saved', currentPrefix: 'Current: ' },
  nav: { store: 'Store', overview: 'Overview', settings: 'Settings' },
  categories: { provider: 'Providers', skill: 'Skills', mcp: 'MCP' },
  window: { close: 'Close', minimize: 'Minimize', maximize: 'Maximize' },
  settings: {
    title: 'Settings',
    close: 'Close',
    tabs: { account: 'Account', general: 'General', about: 'About' },
    account: {
      notSignedIn: 'Not signed in',
      signedIn: 'Signed in',
      disconnected: 'Disconnected',
      logout: 'Log out',
      githubLogin: 'Sign in with GitHub',
      plan: 'Subscription',
      planPro: 'Pro · unlimited private items + advanced analytics',
      planFree: 'Free · upgrade to unlock budget alerts and more',
      upgrade: 'Upgrade to Pro',
      notConfigured: 'Sign-in not configured: missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY.',
      hint: 'Sign in to publish private items, sync your installed skills / MCP / providers / plugins across devices, and get update notifications.',
    },
    general: { theme: 'Theme', dark: 'Dark', light: 'Light', toggle: 'Toggle', targetApp: 'Default target app', language: 'Language', languageSub: 'Choose the interface language' },
    about: { subtitle: 'registry client', docs: 'Docs', github: 'GitHub', checkUpdates: 'Check for updates', checking: 'Checking…', upToDate: 'Up to date', updatesSuffix: 'update(s) available', checkFailed: 'Check failed' },
  },
}

const ja: Dict = {
  detail: { selectHint: '左側から項目を選択して詳細を表示', installedPrefix: 'インストール済み', favorite: 'お気に入り', unfavorite: 'お気に入り解除', copyCmd: 'インストールコマンドをコピー', configCountSuffix: '件の構成 · 左のリストで展開して管理', quality: '品質', tabReview: 'レビュー', tabVersion: 'バージョン', qualityScore: '品質スコア', reviewPoints: 'レビューの要点', autoReviewNote: '自動の品質・安全レビューにより生成 · ユーザーレビューは近日対応', noReview: '自動レビューはまだありません', userReviews: 'ユーザーレビュー', anon: '匿名', reviewOnWeb: 'ウェブ版ストアでレビューを投稿できます', currentVersion: '現在のバージョン', riskLow: '低リスク', riskMedium: '中リスク', riskHigh: '高リスク' },
  health: { title: 'プロバイダーの状態', coolingSuffix: '冷却中', cooldown: '冷却', recoverNow: '今すぐ復旧', healthy: '正常', minutes: '分', seconds: '秒', errAuth: '認証失敗', errRate: 'レート制限', errOverload: '過負荷', errServer: 'サーバーエラー', errNetwork: 'ネットワークエラー' },
  budget: { title: '今月の予算', sub: '支出予算とアラート', edit: '編集', placeholder: '月次予算を設定（空欄で無制限）', ariaLabel: '月次予算', projected: '月末予測', overBudget: '予算超過', nearLimit: '予算上限に接近' },
  usage: { exported: 'エクスポート先', exportFailed: 'エクスポート失敗', exportLabel: '過去30日の使用明細をエクスポート' },
  proxyLog: { title: 'ローカルリレー · リクエストログ', sub: 'レベル順に転送し、失敗時は自動フォールバック', fallback: 'フォールバック' },
  overview: { trend: '使用状況の推移', trendSub: '使用統計', today: '今日', last7: '過去7日', last30: '過去30日', totalCost: '合計費用', totalTokens: '合計トークン', totalRequests: '合計リクエスト', modelCount: 'モデル数', running: '稼働中', stopped: '停止', listenAddr: '待受アドレス', todayRequests: '今日のリクエスト', successRate: '成功率', recentRequests: '最近のリクエスト', viewAll: 'すべて表示', fallback: '（フォールバック）', updatesAvailable: '更新あり', all: 'すべて', update: '更新' },
  pro: {
    budget: { title: '予算と超過アラート', desc: '月次予算を設定し、当月の支出をリアルタイム追跡。月末予測・超過アラート・請求エクスポートに対応。' },
    smartRouting: { title: 'スマートルーティング', desc: '複数アップストリーム間の自動フェイルオーバー。冷却/レート制限中のプロバイダーを回避し、回復後に自動復帰。Freeは最大2系統の基本フェイルオーバー。' },
    keyRotation: { title: 'キーローテーション', desc: '同一プロバイダーに複数のキーを設定し、Proがリクエストごとに切り替えてレート制限を分散します。' },
  },
  common: { install: 'インストール', installed: 'インストール済み', cancel: 'キャンセル', save: '保存', saving: '保存中…', saved: '保存しました', currentPrefix: '現在：' },
  nav: { store: 'ストア', overview: '概要', settings: '設定' },
  categories: { provider: 'プロバイダー', skill: 'スキル', mcp: 'MCP' },
  window: { close: '閉じる', minimize: '最小化', maximize: '最大化' },
  settings: {
    title: '設定',
    close: '閉じる',
    tabs: { account: 'アカウント', general: '一般', about: '情報' },
    account: {
      notSignedIn: '未ログイン',
      signedIn: 'ログイン済み',
      disconnected: '未接続',
      logout: 'ログアウト',
      githubLogin: 'GitHub でログイン',
      plan: 'サブスクリプション',
      planPro: 'Pro · プライベート項目無制限 + 高度な分析',
      planFree: 'Free · アップグレードで予算アラートなどを解放',
      upgrade: 'Pro にアップグレード',
      notConfigured: 'ログイン未設定：VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY がありません。',
      hint: 'ログインすると、プライベート項目の公開、インストール済みのスキル / MCP / プロバイダー / プラグインのデバイス間同期、更新通知が利用できます。',
    },
    general: { theme: 'テーマ', dark: 'ダーク', light: 'ライト', toggle: '切り替え', targetApp: '既定の対象アプリ', language: '言語', languageSub: '表示言語を選択' },
    about: { subtitle: 'registry client', docs: 'ドキュメント', github: 'GitHub', checkUpdates: '更新を確認', checking: '確認中…', upToDate: '最新です', updatesSuffix: '件の更新', checkFailed: '確認に失敗' },
  },
}

const ko: Dict = {
  detail: { selectHint: '왼쪽에서 항목을 선택하면 상세가 표시됩니다', installedPrefix: '설치됨', favorite: '즐겨찾기', unfavorite: '즐겨찾기 해제', copyCmd: '설치 명령 복사', configCountSuffix: '개 구성 · 왼쪽 목록에서 펼쳐 관리', quality: '품질', tabReview: '검토', tabVersion: '버전', qualityScore: '품질 점수', reviewPoints: '검토 요점', autoReviewNote: '자동 품질·안전 검토로 생성 · 사용자 리뷰는 곧 제공', noReview: '자동 검토 없음', userReviews: '사용자 리뷰', anon: '익명', reviewOnWeb: '웹 스토어에서 리뷰를 남길 수 있습니다', currentVersion: '현재 버전', riskLow: '낮은 위험', riskMedium: '중간 위험', riskHigh: '높은 위험' },
  health: { title: '제공자 상태', coolingSuffix: '냉각 중', cooldown: '냉각', recoverNow: '즉시 복구', healthy: '정상', minutes: '분', seconds: '초', errAuth: '인증 실패', errRate: '속도 제한', errOverload: '과부하', errServer: '서버 오류', errNetwork: '네트워크 오류' },
  budget: { title: '이번 달 예산', sub: '지출 예산 및 알림', edit: '편집', placeholder: '월 예산 설정, 비우면 무제한', ariaLabel: '월 예산', projected: '월말 예상', overBudget: '예산 초과', nearLimit: '예산 한도 근접' },
  usage: { exported: '내보냄:', exportFailed: '내보내기 실패', exportLabel: '최근 30일 사용 내역 내보내기' },
  proxyLog: { title: '로컬 릴레이 · 요청 로그', sub: '레벨 순서로 전달, 실패 시 자동 폴백', fallback: '폴백' },
  overview: { trend: '사용량 추이', trendSub: '사용 통계', today: '오늘', last7: '최근 7일', last30: '최근 30일', totalCost: '총 비용', totalTokens: '총 토큰', totalRequests: '총 요청', modelCount: '모델 수', running: '실행 중', stopped: '중지됨', listenAddr: '수신 주소', todayRequests: '오늘 요청', successRate: '성공률', recentRequests: '최근 요청', viewAll: '전체 보기', fallback: '(폴백)', updatesAvailable: '업데이트', all: '전체', update: '업데이트' },
  pro: {
    budget: { title: '예산 및 초과 알림', desc: '월 예산을 설정하고 이번 달 지출을 실시간 추적하며 월말 예측·초과 알림·청구 내보내기를 제공합니다.' },
    smartRouting: { title: '스마트 라우팅', desc: '여러 업스트림 간 자동 장애 조치로 냉각/속도 제한 중인 제공자를 회피하고 정상화되면 자동 복귀합니다. Free는 최대 2개 업스트림 기본 장애 조치입니다.' },
    keyRotation: { title: '키 로테이션', desc: '한 제공자에 여러 키를 설정하면 Pro가 요청마다 번갈아 사용해 속도 제한을 분산합니다.' },
  },
  common: { install: '설치', installed: '설치됨', cancel: '취소', save: '저장', saving: '저장 중…', saved: '저장됨', currentPrefix: '현재: ' },
  nav: { store: '스토어', overview: '개요', settings: '설정' },
  categories: { provider: '제공자', skill: '스킬', mcp: 'MCP' },
  window: { close: '닫기', minimize: '최소화', maximize: '최대화' },
  settings: {
    title: '설정',
    close: '닫기',
    tabs: { account: '계정', general: '일반', about: '정보' },
    account: {
      notSignedIn: '로그인 안 됨',
      signedIn: '로그인됨',
      disconnected: '연결 안 됨',
      logout: '로그아웃',
      githubLogin: 'GitHub로 로그인',
      plan: '구독',
      planPro: 'Pro · 무제한 비공개 항목 + 고급 분석',
      planFree: 'Free · 업그레이드로 예산 알림 등 잠금 해제',
      upgrade: 'Pro로 업그레이드',
      notConfigured: '로그인 미설정: VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY 없음.',
      hint: '로그인하면 비공개 항목 게시, 설치된 스킬 / MCP / 제공자 / 플러그인의 기기 간 동기화, 업데이트 알림을 사용할 수 있습니다.',
    },
    general: { theme: '테마', dark: '다크', light: '라이트', toggle: '전환', targetApp: '기본 대상 앱', language: '언어', languageSub: '인터페이스 언어 선택' },
    about: { subtitle: 'registry client', docs: '문서', github: 'GitHub', checkUpdates: '업데이트 확인', checking: '확인 중…', upToDate: '최신 상태', updatesSuffix: '개 업데이트', checkFailed: '확인 실패' },
  },
}

const es: Dict = {
  detail: { selectHint: 'Selecciona un elemento a la izquierda para ver detalles', installedPrefix: 'Instalado', favorite: 'Favorito', unfavorite: 'Quitar favorito', copyCmd: 'Copiar comando de instalación', configCountSuffix: 'config. · despliega este elemento en la lista izquierda para gestionarlo', quality: 'Calidad', tabReview: 'Revisión', tabVersion: 'Versiones', qualityScore: 'Puntuación de calidad', reviewPoints: 'Puntos de revisión', autoReviewNote: 'Generado por revisión automática de calidad y seguridad · reseñas de usuarios próximamente', noReview: 'Sin revisión automática', userReviews: 'Reseñas de usuarios', anon: 'Anónimo', reviewOnWeb: 'Publica una reseña en la tienda web', currentVersion: 'Versión actual', riskLow: 'Riesgo bajo', riskMedium: 'Riesgo medio', riskHigh: 'Riesgo alto' },
  health: { title: 'Estado del proveedor', coolingSuffix: 'en enfriamiento', cooldown: 'Enfriamiento', recoverNow: 'Recuperar ahora', healthy: 'Correcto', minutes: 'min', seconds: 's', errAuth: 'Fallo de autenticación', errRate: 'Límite de tasa', errOverload: 'Sobrecarga', errServer: 'Error del servidor', errNetwork: 'Error de red' },
  budget: { title: 'Presupuesto del mes', sub: 'presupuesto de gasto y alertas', edit: 'Editar', placeholder: 'Define un presupuesto mensual, en blanco = sin límite', ariaLabel: 'Presupuesto mensual', projected: 'Previsión fin de mes', overBudget: 'Presupuesto superado', nearLimit: 'Cerca del límite' },
  usage: { exported: 'Exportado a', exportFailed: 'Error al exportar', exportLabel: 'Exportar el uso de los últimos 30 días' },
  proxyLog: { title: 'Relé local · registro de solicitudes', sub: 'Reenvía por nivel, con failover automático', fallback: 'Respaldo' },
  overview: { trend: 'Tendencia de uso', trendSub: 'Estadísticas de uso', today: 'Hoy', last7: 'Últimos 7 días', last30: 'Últimos 30 días', totalCost: 'Coste total', totalTokens: 'Tokens totales', totalRequests: 'Solicitudes totales', modelCount: 'Modelos', running: 'En ejecución', stopped: 'Detenido', listenAddr: 'Dirección de escucha', todayRequests: 'Solicitudes de hoy', successRate: 'Tasa de éxito', recentRequests: 'Solicitudes recientes', viewAll: 'Ver todo', fallback: ' (respaldo)', updatesAvailable: 'Actualizaciones', all: 'Todo', update: 'Actualizar' },
  pro: {
    budget: { title: 'Presupuesto y alertas de gasto', desc: 'Define un presupuesto mensual con seguimiento en tiempo real, previsión de fin de mes, alertas de exceso y exportación de facturación.' },
    smartRouting: { title: 'Enrutamiento inteligente', desc: 'Conmutación por error automática entre upstreams, evitando proveedores en enfriamiento/limitados y volviendo al recuperarse. Free es failover básico de dos upstreams.' },
    keyRotation: { title: 'Rotación de claves', desc: 'Configura varias claves por proveedor; Pro las rota por solicitud para repartir los límites de tasa.' },
  },
  common: { install: 'Instalar', installed: 'Instalado', cancel: 'Cancelar', save: 'Guardar', saving: 'Guardando…', saved: 'Guardado', currentPrefix: 'Actual: ' },
  nav: { store: 'Tienda', overview: 'Resumen', settings: 'Ajustes' },
  categories: { provider: 'Proveedores', skill: 'Habilidades', mcp: 'MCP' },
  window: { close: 'Cerrar', minimize: 'Minimizar', maximize: 'Maximizar' },
  settings: {
    title: 'Ajustes',
    close: 'Cerrar',
    tabs: { account: 'Cuenta', general: 'General', about: 'Acerca de' },
    account: {
      notSignedIn: 'Sin iniciar sesión',
      signedIn: 'Sesión iniciada',
      disconnected: 'Desconectado',
      logout: 'Cerrar sesión',
      githubLogin: 'Iniciar sesión con GitHub',
      plan: 'Suscripción',
      planPro: 'Pro · elementos privados ilimitados + análisis avanzado',
      planFree: 'Free · mejora para desbloquear alertas de presupuesto y más',
      upgrade: 'Mejorar a Pro',
      notConfigured: 'Inicio de sesión no configurado: falta VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY.',
      hint: 'Inicia sesión para publicar elementos privados, sincronizar tus habilidades / MCP / proveedores / plugins instalados entre dispositivos y recibir avisos de actualización.',
    },
    general: { theme: 'Tema', dark: 'Oscuro', light: 'Claro', toggle: 'Cambiar', targetApp: 'App de destino por defecto', language: 'Idioma', languageSub: 'Elige el idioma de la interfaz' },
    about: { subtitle: 'registry client', docs: 'Documentación', github: 'GitHub', checkUpdates: 'Buscar actualizaciones', checking: 'Buscando…', upToDate: 'Actualizado', updatesSuffix: 'actualización(es)', checkFailed: 'Error al buscar' },
  },
}

export const messages: Record<Locale, Dict> = { zh, en, ja, ko, es }
